### ISSUE TITLE
Cannot read property 'getUserMedia' of undefined

### ISSUE THREAD

**Issue by misterunknown** [lamarios/monopoly#1]
When I open my instance URL in the browser, this javascript error occurs:
![image](https://user-images.githubusercontent.com/3264829/79640134-2ab4ff00-8190-11ea-9bf1-c579739dc4ef.png)
I started a container as follows:
```
docker run --rm -ti -e "HTTP=true" -e "PORT=8080" -p "8080:8080" gonzague/monopoly
```
The network tab shows no failed requests.

**Comment by 5hay** [comment]
I have not yet installed it for myself, but it's probably because of the `HTTP=true`. Accessing the user's camera is only allowed in HTTPS environments.

**Comment by misterunknown** [comment]
Correct, if I use the HTTPS variant, it works. This might be worth a hint in the README.

**Comment by lamarios** [comment]
It is, twice ;)
