### ISSUE TITLE
game tokens laggy when dragged

### ISSUE THREAD

**Issue by Trevor159** [lamarios/monopoly#18]
On both my self hosted version and the demo the game the tokens are "laggy". Laggy might not be the correct term so here is a gif demonstrating what I mean. This happens to me on both chrome and firefox.

![](https://i.imgur.com/JVVxIfq.gif)

**Comment by lamarios** [comment]
I'll have to look into that, i know why it happens but because of the way I coded the game (quickly and dirty) the fix might not  be that simple.

**Comment by lamarios** [comment]
ok, should be fixed in latest commit, images should be published too.
