### ISSUE TITLE
Stuck on Loading Game

### ISSUE THREAD

**Issue by Sushiman42** [lamarios/monopoly#19]
While using the manager, I am able to successfully start a game and produce a link, but then the app hangs on a white screen after Loading Game. Same behavior when just launching the game. Docker containers in both instances aren't throwing any errors. Only output is:
```
request received: /
request received: /jsx.6aed5b15.js
new connection
```
on refresh.

**Comment by lamarios** [comment]
Are you using a reverse proxy to access the manager ?

**Comment by Sushiman42** [comment]
I've used multiple configurations, but I can replicate this behavior with the default config:

```
docker run -p "8443:8443" gonzague/monopoly
```

**Comment by lamarios** [comment]
Hmmm, It works fine for me on both chrome and firefox.

Which browser are you using ? Do you use any extensions that could potentially block web sockets and/or webRTC ? Do you see any error in the browser console and/or the browser network console (F12) ? Which OS are you running the container on ?

**Comment by Sushiman42** [comment]
Good call on the browser console suggestion. I spent a while troubleshooting with a variety of stock browsers and configs, and it turns out it's a combination of a few problems. When using the flag `HTTP=true`, the site is inaccessible from within the local network (and externally), due to a `TypeError: navigator.mediaDevices is undefined`. When I ran the manager through a https reverse proxy with the `HTTP=true` variable, and websocket support enabled, I was finally able to reliably access the games and the manager.

Thanks for the suggestions, cheers.

**Comment by Sushiman42** [comment]
I have to assume the `navigator.mediaDevices` is because, as you noted in the documentation, the video support fails when not using HTTPS. I had just assumed that the game would still work, but that could be a browser thing.

**Comment by lamarios** [comment]
Alright. It's worth looking at it so at least it can work in HTTP mode.

**Comment by Sushiman42** [comment]
I'm just happy it works through my reverse proxy. In any case, I'm going to close this issue, since I've resolved the issue on my end.
