### ISSUE TITLE
Unable to run Docker container

### ISSUE THREAD

**Issue by vedangwartikar** [lamarios/monopoly#27]
Getting error as 
`standard_init_linux.go:211: exec user process caused "exec format error"`

After looking it up online, it's related to shebang (#!). Any other way to get past this manually?

**Comment by lamarios** [comment]
I assume you're trying to run the game.

which command did you use to run the game ?  I'm not sure which shebang you're referring to ? I don't believe there's any in the code.

**Comment by Zir0h** [comment]
Are you trying to run the docker gonzague/monopoly-manager amd64 image on an arm machine?

**Comment by vedangwartikar** [comment]
> Are you trying to run the docker gonzague/monopoly-manager amd64 image on an arm machine?
Yes I am currently trying this out on an ARM based VM

**Comment by vedangwartikar** [comment]
> I assume you're trying to run the game.
> 
> which command did you use to run the game ? I'm not sure which shebang you're referring to ? I don't believe there's any in the code.

I was just trying to build a container using docker-compose

**Comment by lamarios** [comment]
You'll need to build the container yourself. Docker run is to run the container. Not build it. 

See here: https://github.com/lamarios/monopoly/issues/21

**Comment by lamarios** [comment]
In short cd to the game folder the run (from memory)

```
docker build -t monopoly .
```

Then to run it
```
docker run -it monopoly 
```
