### ISSUE TITLE
fontawesome-pro in game client

### ISSUE THREAD

**Issue by Simber1** [lamarios/monopoly#3]
I saw the commit saying you have removed it but it's still there and causing me issues.
https://github.com/lamarios/monopoly/blob/622d3e50b7d3d6449ede0391986fce4d5769032e/game/client/package-lock.json#L1062

Edit: https://github.com/lamarios/monopoly/blob/622d3e50b7d3d6449ede0391986fce4d5769032e/game/client/package.json#L19

**Comment by lamarios** [comment]
It should be fixed now
