### ISSUE TITLE
Unable to see changes

### ISSUE THREAD

**Issue by tazim-sikder** [lamarios/monopoly#37]
I am running the project on my localhost, and I am trying to add my own edits to it(I am making my own custom clone) but when I make changes to the code, the changes are not showing on localhost: 8443

**Comment by lamarios** [comment]
What did you change ?

**Comment by tazim-sikder** [comment]
I tried to change the words on the welcome modal box, "Welcome to an online Monopoly game !" The changes did not show on the screen.

**Comment by lamarios** [comment]
when you make changes to the game/client folder, you need to run 
```
npm run dev
```
or 
```
npm run build
```

from the game/client folder. That will update the static folder in game/server
