### ISSUE TITLE
Properties mortgage option - feature request

### ISSUE THREAD

**Issue by tamet83** [lamarios/monopoly#7]
Hi,

today me and my friends played again at Monopoly.
We all thank you for you work, we spent again very good time together.

During the game one of the player ended his money and he Mortgage one of his card to the bank.
We noticed that on the back of the card there isn't any instruction about Mortgage.
Is it possible implement this option, could be also useful create some sort of mark on the card to notice it.

[Here ](https://monopoly.fandom.com/wiki/Mortgage)the link to the game rule, in case you need to review it.

Again, thanks for your work.

**Comment by lamarios** [comment]
Alright that seems simple enough. I'll have a look at it.

**Comment by lamarios** [comment]
Ok, I made the changes and pushed the latest docker image. Check it out and let me know if the implementation works for you.

**Comment by tamet83** [comment]
Wow, amazing job.
We all thank you :)

I'll open a new post to ask you another thing if you don't mind.
let me know what do you think about it.

Meanwhile thanks again for your amazing job.
