### ISSUE TITLE
Jail free pass - Feature request

### ISSUE THREAD

**Issue by tamet83** [lamarios/monopoly#8]
Hi again,

yesterday we noticed that the game doesn't have any way, except the log, to see if one player has a jail free pass or not.

We were thinking if there is a way to have some sort of mark to notify all player that the free pass has been used or not.

Thanks again :)

**Comment by lamarios** [comment]
Yeah. This one has been bothering me for a while. I'll look at it tomorrow.

**Comment by lamarios** [comment]
Ok, it's in the last docker image (or my demo as well)

I added the card to the player board, you can either use it or send it

[Imgur](https://imgur.com/D0DnHOn)

**Comment by tamet83** [comment]
Sorry I didn’t answer you.
Thank you for your time again!
